
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('tripsTable').del()
    .then(function () {
      // Inserts seed entries
      return knex('tripsTable').insert([
        { tripName: "Alatna River to Noatak River", startDate:'2019-01-18', endDate: '2019-01-20', location:'Brooks Range, AK', description:"Want truly wild lands? Deep in the Brooks Range in the land of midnight sun (and winter darkness), the 8.4-million-acre Gates of the Arctic National Park has no roads and no real trails to speak of. This place truly belongs to the wildlife: Brown bears scavenge the tundra for food, packs of wolves hunt down big and small game, Dall sheep haunt the highlands, and herds of caribou thunder across the park in their great, romantic migrations. Backpacking trips are only limited by time and wilderness experience, but one of the most popular routes traverses the high, remote (150 miles from the nearest village) headwaters of the Alatna and Noatak Rivers. Up here among the wide-open slopes and the odd, sedimentary formations of the mountains, backpackers can immerse themselves in the deep timelessness of the planet and are more or less guaranteed to witness the comings and goings of Alaska’s wildlife. (Note: This particular trip is offered by hiking guides Arctic Wild, a good option since floatplane logistics and keeping wildlife at bay can be difficult.)"},
        { tripName: "Brown Pass", startDate:'2018-10-23', endDate: '2018-10-25', location:'Glacier National Park, MT', description:"The elegant mountains here were—no surprise—carved out by glaciers receding after the last ice age, and those melting ice sheets also left deep, serene lakes in their wake. This hike takes in both peaks and lakeshore. Tucked away in the northwest section of the park, the backpacking trip joins Kintla Lake, located far from the west entrance via a 40-mile drive down dirt roads, with Bowman Lake, which is only slightly closer to civilization. Along the way, it traverses the quiet shores of each and links the two via the high wilds of Brown Pass deep in a park where the wildlife still runs the show. (Carry bear spray; Glacier’s grizzlies don’t see many humans here.) But the untrammeled alpine here is well worth the hike: Stroll through the riot of wild flowers in the meadows, and don’t miss the 800-foot Hole in the Wall waterfall."},
        { tripName: "The Grand Loop", startDate:'2018-12-09', endDate: '2018-12-11', location:'Rocky Mountain, CO', description:"It's tough to choose just one classic backpacking trip in this ever popular park, which straddles the Continental Divide and preserves the heart of the lower 48’s longest mountain range. But this trip gets into the heart of the place, starting and ending in popular tourist spots but soon losing the crowds as it climbs into silent nooks and wide-open expanses of high country. Beginning at Bear Lake on the east side of the divide, the trail climbs up to the exposed reaches of Flattop Mountain, where bighorn sheep roam and deadly lightning storms can whip up in minutes (get off the peak before noon to avoid afternoon squalls). It then dives into remote regions of the park before stopping at Grand Lake, where the luxury-minded can stop for an espresso or even a soft bed, before once again returning to the wilds and topping back over the divide to the start. That voyage takes in everything the park has to offer, from quiet alpine lakes to meadows with herds of elk to soaring granite cliffs."}
      ]);
    });
};
